import 'package:flutter/material.dart';

import 'chavrusa_directory_theme.dart';
import 'design_direction.dart';

/// Ten distinct enterprise-grade design directions for Lilmod Ulilamed.
abstract final class DesignDirections {
  static const all = <DesignDirection>[
    chavrusaDirectory,
    discourseMinimal,
    bloombergEditorial,
    slackWorkspace,
    githubDiscussions,
    appleGrouped,
    materialExpressive,
    darkPro,
    academicJournal,
    nordicMinimal,
    enterpriseSaas,
  ];

  static DesignDirection? byId(String id) {
    for (final d in all) {
      if (d.id == id) return d;
    }
    return null;
  }

  /// Default shipped theme — matches the Chavrusa directory (brutalist chrome).
  static const chavrusaDirectory = DesignDirection(
    id: 'chavrusa-directory',
    name: 'Chavrusa Directory',
    concept: 'Square cards, navy accent borders, brutalist buttons — directory-first.',
    evokes: 'Chavrusa board, enterprise listings',
    primary: ChavrusaDirectoryTheme.blue,
    background: Colors.white,
    surface: Colors.white,
    surfaceMuted: Color(0xFFF4F6F8),
    ink: ChavrusaDirectoryTheme.ink,
    body: ChavrusaDirectoryTheme.ink,
    muted: ChavrusaDirectoryTheme.muted,
    border: ChavrusaDirectoryTheme.line,
    accent: ChavrusaDirectoryTheme.blue,
    cornerRadius: 0,
    density: 0.95,
    useShadow: false,
    useBorder: true,
    pillTags: false,
    navStyle: DesignNavStyle.flatBorder,
    typography: DesignTypography.inter,
    isDark: false,
    useBrutalistChrome: true,
  );

  static const discourseMinimal = DesignDirection(
    id: 'discourse-minimal',
    name: 'Discourse Minimal',
    concept: 'Flat lists, hairline borders, one blue accent — built for reading.',
    evokes: 'Discourse, Basecamp, Linear',
    primary: Color(0xFF2563EB),
    background: Color(0xFFFAFAFA),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFF4F4F5),
    ink: Color(0xFF18181B),
    body: Color(0xFF3F3F46),
    muted: Color(0xFF71717A),
    border: Color(0xFFE4E4E7),
    accent: Color(0xFF2563EB),
    cornerRadius: 8,
    density: 0.92,
    useShadow: false,
    useBorder: true,
    pillTags: false,
    navStyle: DesignNavStyle.flatBorder,
    typography: DesignTypography.inter,
    isDark: false,
  );

  static const bloombergEditorial = DesignDirection(
    id: 'bloomberg-editorial',
    name: 'Bloomberg Editorial',
    concept: 'Serif headlines, navy + gold — authoritative financial press.',
    evokes: 'Bloomberg, Financial Times, The Economist',
    primary: Color(0xFF0A1628),
    background: Color(0xFFF7F5F0),
    surface: Color(0xFFFFFBF5),
    surfaceMuted: Color(0xFFEDE8DF),
    ink: Color(0xFF0A1628),
    body: Color(0xFF2C3340),
    muted: Color(0xFF6B7280),
    border: Color(0xFFD6D0C4),
    accent: Color(0xFFB8860B),
    cornerRadius: 4,
    density: 1.05,
    useShadow: false,
    useBorder: true,
    pillTags: false,
    navStyle: DesignNavStyle.underline,
    typography: DesignTypography.serif,
    isDark: false,
  );

  /// Authentic Slack product palette — brand guidelines + design-system tokens.
  /// Aubergine #4A154B sidebar/chrome, Lato UI, link blue #1264A3, borders #E8E8E8.
  static const slackWorkspace = DesignDirection(
    id: 'slack-workspace',
    name: 'Slack Workspace',
    concept: 'Aubergine workspace banner, Lato type, channel-list density.',
    evokes: 'Slack mobile Home tab',
    primary: Color(0xFF4A154B),
    background: Color(0xFFFFFFFF),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFF8F8F8),
    ink: Color(0xFF1D1C1D),
    body: Color(0xFF616061),
    muted: Color(0xFF868686),
    border: Color(0xFFE8E8E8),
    accent: Color(0xFF1264A3),
    cornerRadius: 4,
    density: 0.88,
    useShadow: false,
    useBorder: true,
    pillTags: true,
    navStyle: DesignNavStyle.filled,
    typography: DesignTypography.lato,
    isDark: false,
  );

  static const githubDiscussions = DesignDirection(
    id: 'github-discussions',
    name: 'GitHub Discussions',
    concept: 'Monochrome structure with a single green action accent.',
    evokes: 'GitHub, GitLab issues',
    primary: Color(0xFF24292F),
    background: Color(0xFFF6F8FA),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFF6F8FA),
    ink: Color(0xFF24292F),
    body: Color(0xFF57606A),
    muted: Color(0xFF656D76),
    border: Color(0xFFD0D7DE),
    accent: Color(0xFF1A7F37),
    cornerRadius: 6,
    density: 0.9,
    useShadow: false,
    useBorder: true,
    pillTags: false,
    navStyle: DesignNavStyle.flatBorder,
    typography: DesignTypography.mono,
    isDark: false,
  );

  static const appleGrouped = DesignDirection(
    id: 'apple-grouped',
    name: 'Apple HIG Native',
    concept: 'Grouped inset lists, system typography, iOS Settings feel.',
    evokes: 'Apple Mail, iOS Settings, Apple Developer Forums',
    primary: Color(0xFF007AFF),
    background: Color(0xFFF2F2F7),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFE5E5EA),
    ink: Color(0xFF000000),
    body: Color(0xFF3C3C43),
    muted: Color(0xFF8E8E93),
    border: Color(0xFFC6C6C8),
    accent: Color(0xFF007AFF),
    cornerRadius: 10,
    density: 1.0,
    useShadow: false,
    useBorder: false,
    pillTags: false,
    navStyle: DesignNavStyle.filled,
    typography: DesignTypography.system,
    isDark: false,
  );

  static const materialExpressive = DesignDirection(
    id: 'material-expressive',
    name: 'Material 3 Expressive',
    concept: 'Tonal surfaces, rounded containers, vibrant primary container.',
    evokes: 'Google apps, Material You',
    primary: Color(0xFF6750A4),
    background: Color(0xFFFFFBFE),
    surface: Color(0xFFFFFBFE),
    surfaceMuted: Color(0xFFE7E0EC),
    ink: Color(0xFF1C1B1F),
    body: Color(0xFF49454F),
    muted: Color(0xFF79747E),
    border: Color(0xFFCAC4D0),
    accent: Color(0xFF6750A4),
    cornerRadius: 16,
    density: 1.08,
    useShadow: true,
    useBorder: false,
    pillTags: true,
    navStyle: DesignNavStyle.elevated,
    typography: DesignTypography.inter,
    isDark: false,
  );

  static const darkPro = DesignDirection(
    id: 'dark-pro',
    name: 'Dark Pro',
    concept: 'Dark-first, high-contrast text, cyan accent for focus states.',
    evokes: 'Discord, Notion dark, Pro tools',
    primary: Color(0xFF22D3EE),
    background: Color(0xFF0F0F10),
    surface: Color(0xFF18181B),
    surfaceMuted: Color(0xFF27272A),
    ink: Color(0xFFFAFAFA),
    body: Color(0xFFD4D4D8),
    muted: Color(0xFFA1A1AA),
    border: Color(0xFF3F3F46),
    accent: Color(0xFF22D3EE),
    cornerRadius: 8,
    density: 0.92,
    useShadow: false,
    useBorder: true,
    pillTags: false,
    navStyle: DesignNavStyle.darkBar,
    typography: DesignTypography.inter,
    isDark: true,
  );

  static const academicJournal = DesignDirection(
    id: 'academic-journal',
    name: 'Academic Journal',
    concept: 'Warm paper tones, serif body, scholarly margins and hierarchy.',
    evokes: 'JSTOR, university portals, Sefaria web',
    primary: Color(0xFF5C4033),
    background: Color(0xFFF5F0E6),
    surface: Color(0xFFFFFCF5),
    surfaceMuted: Color(0xFFEDE4D4),
    ink: Color(0xFF2C1810),
    body: Color(0xFF4A3728),
    muted: Color(0xFF8B7355),
    border: Color(0xFFD4C4A8),
    accent: Color(0xFF8B4513),
    cornerRadius: 6,
    density: 1.12,
    useShadow: false,
    useBorder: true,
    pillTags: false,
    navStyle: DesignNavStyle.underline,
    typography: DesignTypography.serif,
    isDark: false,
  );

  static const nordicMinimal = DesignDirection(
    id: 'nordic-minimal',
    name: 'Nordic Minimal',
    concept: 'Cool greys, generous whitespace, whisper-thin dividers.',
    evokes: 'Scandinavian SaaS, Stripe docs, Vercel',
    primary: Color(0xFF0F172A),
    background: Color(0xFFF8FAFC),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFF1F5F9),
    ink: Color(0xFF0F172A),
    body: Color(0xFF475569),
    muted: Color(0xFF94A3B8),
    border: Color(0xFFE2E8F0),
    accent: Color(0xFF64748B),
    cornerRadius: 12,
    density: 1.15,
    useShadow: false,
    useBorder: true,
    pillTags: false,
    navStyle: DesignNavStyle.flatBorder,
    typography: DesignTypography.inter,
    isDark: false,
  );

  static const enterpriseSaas = DesignDirection(
    id: 'enterprise-saas',
    name: 'Enterprise SaaS',
    concept: 'Navy indigo brand, crisp cards, structured metadata rows.',
    evokes: 'Salesforce, Atlassian, enterprise dashboards',
    primary: Color(0xFF1E3A8A),
    background: Color(0xFFF0F4FA),
    surface: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFE8EEF7),
    ink: Color(0xFF0F172A),
    body: Color(0xFF334155),
    muted: Color(0xFF64748B),
    border: Color(0xFFCBD5E1),
    accent: Color(0xFF3B82F6),
    cornerRadius: 10,
    density: 1.0,
    useShadow: true,
    useBorder: true,
    pillTags: true,
    navStyle: DesignNavStyle.elevated,
    typography: DesignTypography.inter,
    isDark: false,
  );
}
